config/routes.rb
Rails.application.routes.draw do
  get 'books/search', to: 'books#search', as: 'search_books'
  resources :books
  resources :users
  resources :distributors
  resources :publishers
  resources :categories
  resources :book_types
  resources :stock_books
  resources :receive_books
  resources :return_books
  resources :payment_books
  resources :sell_books
  devise_for :users
  root to: 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end
  
  # GET /books/Search
  def search
    if params[:search].present?
      @books = Book.where('title LIKE ? OR author LIKE ? OR category_id LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @books = Book.all
    end
  end
  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :category_id, :price, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="<%= book.image_url %>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= book.title %></h5>
    <p class="card-text">Author: <%= book.author %></p>
    <p class="card-text">Publisher: <%= book.publisher.name %></p>
    <p class="card-text">Category: <%= book.category.name %></p>
    <p class="card-text">Book Type: <%= book.book_type.name %></p>
    <p class="card-text">Price: <%= book.price %></p>
    <p class="card-text">Stock: <%= book.stock %></p>
    <p class="card-text">Description: <%= book.description %></p>
    <p class="card-text">
      <%= link_to "Show this book", book %>
    </p>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to 'Home', books_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Data User (Kasir)', users_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Data Distributor', distributors_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Data Penerbit', publishers_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Data Kategori Buku', categories_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Data Jenis Buku', book_types_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Data Buku', books_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Pencarian Buku (1)', search_books_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Pencarian Buku (2)', search_books_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Kontrol Stok Buku', stock_books_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Transaksi Penerimaan', receive_books_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Transaksi Retur', return_books_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Transaksi Pembayaran', payment_books_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Transaksi Penjualan', sell_books_path %>
        </li>
      </ul>
    </div>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <ul class="nav flex-column">
        <!-- Your navigation links here -->
      </ul>
    </div>
    <div class="col-md-9">
      <h1>Selamat datang !</h1>
      <p>Anda login sebagai Admin</p>
      <p style="color: green"><%= notice %></p>

      <h1>Books</h1>

      <%= form_with url: search_books_path, method: :get do |f| %>
        <%= f.label :search, 'Search for books:' %>
        <%= f.text_field :search %>
        <%= f.submit 'Search' %>
      <% end %>
      
      <div id="books">
        <%= render partial: 'book', collection: @books %>
      </div>

      <%= link_to "New book", new_book_path %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>